mysql:
  database: cloud
  host: mysql
  port: 3306
  username: root
  password: 123456

mongodb:
  hosts: mongodb-mongos:27017
  database: iot
  username: root
  password: 123456

redis:
  host: redis
  port: 6379
  password: 123456
  database: 0
  timeout: 30000
  
clickhouse:
  database: test
  max_batch_size: 5000
  max_in_flight_requests: 2
  max_buffered_requests: 20000
  # Supports fixed value or simple multiplication expression.
  max_batch_size_in_bytes: 1024 * 1024 * 10
  max_time_in_buffer_ms: 5 * 1000
  max_record_size_in_bytes: 1024 * 1024 * 3

job:
  jobIntervalMs:
  # 任务执行间隔，单位毫秒 jobName:intervalMs
    - FileReadJob:10000
    - dimData:10000
  jobCheckpointIntervalMs: 
    - readFile:10000
  jobParallelism: 
    - readFile:1
  
